[package]
name = "velyst-testing"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.18", features = ["2d"], default-features = false }
bevy_vello = "0.13"
velyst = { git = "https://github.com/voxell-tech/velyst" }
bevy_motiongfx = { git = "https://github.com/voxell-tech/motiongfx" }

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
debug = false
strip = "debuginfo"
lto = "fat"
panic = "abort"
codegen-units = 1
